export const COLLEGES = [
  // Maharashtra - Mumbai
  "VJTI Mumbai (Veermata Jijabai Technological Institute)",
  "SPIT Mumbai (Sardar Patel Institute of Technology)",
  "DJSCE Mumbai (Dwarkadas J. Sanghvi College of Engineering)",
  "TSEC Mumbai (Thadomal Shahani Engineering College)",
  "VESIT Mumbai (Vivekanand Education Society's Institute of Technology)",
  "K. J. Somaiya College of Engineering, Mumbai",
  "ICT Mumbai (Institute of Chemical Technology)",
  "Fr. Conceicao Rodrigues College of Engineering, Mumbai",
  "NMIMS MPSTME, Mumbai",
  "Sardar Patel College of Engineering, Mumbai (SPCE)",
  "RAIT Navi Mumbai",
  
  // Maharashtra - Pune
  "COEP Technological University, Pune",
  "PICT Pune (Pune Institute of Computer Technology)",
  "VIT Pune (Vishwakarma Institute of Technology)",
  "MIT WPU Pune (MIT World Peace University)",
  "Army Institute of Technology, Pune",
  "D. Y. Patil College of Engineering, Pune",
  "Cummins College of Engineering for Women, Pune",
  
  // Maharashtra - Other
  "Walchand College of Engineering, Sangli",
  "SGGSIE&T Nanded",
  "Government College of Engineering, Karad",
  "Government College of Engineering, Aurangabad",
  "RCOEM Nagpur (Ramdeobaba College of Engineering)",
  "VNIT Nagpur",
  
  // IITs (Indian Institutes of Technology)
  "IIT Bombay",
  "IIT Delhi",
  "IIT Madras",
  "IIT Kharagpur",
  "IIT Kanpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT BHU (Varanasi)",
  "IIT Indore",
  "IIT Ropar",
  "IIT Mandi",
  "IIT Gandhinagar",
  "IIT Patna",
  "IIT Bhubaneswar",
  "IIT Tirupati",
  "IIT Palakkad",
  "IIT Jodhpur",
  "IIT Bhilai",
  "IIT Goa",
  "IIT Jammu",
  "IIT Dharwad",
  
  // BITS
  "BITS Pilani",
  "BITS Pilani (Goa Campus)",
  "BITS Pilani (Hyderabad Campus)",
  
  // NITs
  "NIT Trichy",
  "NIT Surathkal",
  "NIT Warangal",
  "NIT Rourkela",
  "NIT Calicut",
  "MNIT Jaipur",
  "MNNIT Allahabad",
  "NIT Kurukshetra",
  "NIT Durgapur",
  "NIT Silchar",
  "NIT Delhi",
  "NIT Jalandhar",
  "NIT Hamirpur",
  "NIT Raipur",
  "NIT Patna",
  "NIT Goa",
  "NIT Jamshedpur",
  "SVNIT Surat",
  
  // IIITs
  "IIIT Hyderabad",
  "IIIT Bangalore",
  "IIIT Allahabad",
  "IIIT Delhi",
  "IIITM Gwalior",
  "IIITDM Kancheepuram",
  "IIIT Pune",
  "IIIT Kota",
  "IIIT Sri City",
  "IIIT Vadodara",
  "IIIT Lucknow",
  
  // Other Top National Universities
  "IISc Bangalore",
  "DTU Delhi",
  "NSUT Delhi",
  "PEC Chandigarh",
  "DAIICT Gandhinagar",
  "Nirma University, Ahmedabad",
  "PDEU Gandhinagar",
  "VIT Vellore",
  "SRM Institute of Science and Technology",
  "Manipal Institute of Technology",
  "RVCE Bangalore",
  "PES University, Bangalore",
  "BMS College of Engineering, Bangalore",
  "Thapar Institute of Engineering and Technology, Patiala",
  "PSG College of Technology, Coimbatore",
  "Amrita Vishwa Vidyapeetham",
  
  // Fallback
  "Other"
];
