"use client";

import React, { useState } from "react";
import Logo from "@/components/Logo";

const Guides = () => (
  <>
    {/* Page Safe Area (12mm) */}
    <div className="guide-line absolute border-[0.5pt] border-dotted border-blue-500 z-50 pointer-events-none"
         style={{ top: '12mm', left: '12mm', right: '12mm', bottom: '12mm' }} />

    {/* QR Physical Bounds (approx 74x74mm bounding box to ensure 70mm QR clears) */}
    <div className="guide-line absolute border-[0.5pt] border-dashed border-red-500 z-50 pointer-events-none left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"
         style={{ width: '74mm', height: '74mm' }} />
  </>
);

export default function QRSignPrintPage() {
  const [showGuides, setShowGuides] = useState(true);

  return (
    <div className="min-h-screen bg-neutral-200 py-8 flex flex-col items-center print:py-0 print:bg-transparent screen-only-container">
      <style dangerouslySetInnerHTML={{__html: `
        @page {
          size: A5 portrait;
          margin: 0;
        }
        @media print {
          html, body {
            margin: 0 !important;
            padding: 0 !important;
            background: white !important;
          }
          .screen-only-container {
            padding: 0 !important;
            background: white !important;
          }
          .no-print {
            display: none !important;
          }
          .print-sheet {
            width: 148mm !important;
            height: 210mm !important;
            margin: 0 !important;
            padding: 0 !important;
            box-sizing: border-box !important;
            page-break-after: always !important;
            break-after: page !important;
            box-shadow: none !important;
            justify-content: center !important;
            align-items: center !important;
          }
          .guide-line {
            display: none !important;
          }
        }
      `}} />

      <div className="no-print flex flex-col items-center gap-4 mb-8">
        <h1 className="text-xl font-bold tracking-widest uppercase text-gray-800">QR SIGN</h1>
        <div className="flex gap-4">
          <button
            onClick={() => setShowGuides(!showGuides)}
            className="bg-white border border-gray-300 text-black px-4 py-2 rounded text-sm hover:bg-gray-50 transition-colors"
          >
            {showGuides ? "Hide Guides" : "Show Guides"}
          </button>
          <button
            onClick={() => window.print()}
            className="bg-black text-white px-4 py-2 rounded text-sm hover:bg-neutral-800 transition-colors"
          >
            Print / Save PDF
          </button>
        </div>
      </div>

      <div className="print-sheet bg-[#F2F0EA] text-[#0F0F0E] shadow-xl box-border relative flex flex-col"
           style={{ width: '148mm', height: '210mm', WebkitPrintColorAdjust: 'exact', printColorAdjust: 'exact' }}>

        {showGuides && <Guides />}

        {/* Content Container with 12mm padding */}
        <div className="flex-1 flex flex-col items-center text-center justify-between" style={{ padding: '12mm' }}>

          {/* HEADER */}
          <div className="flex flex-col items-center mt-2">
            <Logo className="w-[35mm] h-auto text-[#0F0F0E] mb-6" />
            <h1 style={{ fontFamily: 'var(--font-display-face)', fontSize: '24pt', lineHeight: '1.1' }} className="font-bold tracking-tight mb-3 uppercase">
              Ready to find<br />your team?
            </h1>
            <p style={{ fontFamily: 'var(--font-ui)', fontSize: '13pt' }} className="text-[#161615] font-medium">
              Find your next hackathon team.
            </p>
          </div>

          {/* QR CODE */}
          <div className="flex flex-col items-center">
            {/* The QR SVG is rendered with a 70x70mm dimension and a slight white border if needed,
                though the SVG itself has a margin of 1 generated by qrcode */}
            <div className="bg-white p-2 rounded shadow-sm border border-gray-200 flex items-center justify-center mb-4"
                 style={{ width: '70mm', height: '70mm' }}>
              <img
                src="/expo/hackermate-qr.svg"
                alt="HackerMate QR Code"
                style={{ width: '100%', height: '100%', objectFit: 'contain' }}
              />
            </div>
            <div style={{ fontFamily: 'var(--font-code)', fontSize: '14pt' }} className="font-bold tracking-wide text-[#0F0F0E]">
              hackermate.in
            </div>
            <div style={{ fontFamily: 'var(--font-ui)', fontSize: '10pt' }} className="text-[#737069] font-medium mt-1">
              Scan to join HackerMate
            </div>
          </div>

          {/* FOOTER */}
          <div className="flex justify-center items-center w-full mt-4">
            <div className="uppercase tracking-widest text-[#737069] font-medium flex gap-2 items-center" style={{ fontFamily: 'var(--font-code)', fontSize: '7.5pt' }}>
              <span>FIND</span>
              <span className="text-[#B4F461] opacity-70">→</span>
              <span>REVIEW</span>
              <span className="text-[#B4F461] opacity-70">→</span>
              <span>MERGE</span>
              <span className="text-[#B4F461] opacity-70">→</span>
              <span>BUILD</span>
              <span className="text-[#B4F461] opacity-70">→</span>
              <span>SHIP</span>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
