import { Builder, Challenge } from "./types";

export const BUILDERS: Builder[] = [
  {
    id: "aarav",
    name: "Aarav",
    role: "Frontend Developer",
    skills: ["React", "TypeScript", "Next.js"],
    covers: ["Frontend", "UI/UX"],
    needsSupportWith: "Backend",
  },
  {
    id: "priya",
    name: "Priya",
    role: "Backend Developer",
    skills: ["Node.js", "PostgreSQL", "REST APIs"],
    covers: ["Backend"],
    needsSupportWith: "UI/UX",
  },
  {
    id: "karan",
    name: "Karan",
    role: "AI/ML Engineer",
    skills: ["Python", "PyTorch", "LLMs"],
    covers: ["AI/ML", "Data"],
    needsSupportWith: "Cloud/DevOps",
  },
  {
    id: "meera",
    name: "Meera",
    role: "UI/UX Designer",
    skills: ["Figma", "User Research", "Prototyping"],
    covers: ["UI/UX", "Product"],
    needsSupportWith: "Backend",
  },
  {
    id: "rohan",
    name: "Rohan",
    role: "Product Strategist",
    skills: ["Research", "Roadmapping", "Pitching"],
    covers: ["Product", "Growth"],
    needsSupportWith: "Frontend",
  },
  {
    id: "ananya",
    name: "Ananya",
    role: "DevOps Engineer",
    skills: ["Docker", "AWS", "CI/CD"],
    covers: ["Cloud/DevOps", "Backend"],
    needsSupportWith: "Product",
  },
  {
    id: "vikram",
    name: "Vikram",
    role: "Mobile Developer",
    skills: ["Flutter", "Firebase", "REST"],
    covers: ["Mobile", "Frontend"],
    needsSupportWith: "UI/UX",
  },
  {
    id: "isha",
    name: "Isha",
    role: "Full-Stack Developer",
    skills: ["Next.js", "Node.js", "PostgreSQL"],
    covers: ["Frontend", "Backend"],
    needsSupportWith: "Product",
  },
  {
    id: "neel",
    name: "Neel",
    role: "Data Engineer",
    skills: ["Python", "SQL", "Pandas"],
    covers: ["Data"],
    needsSupportWith: "Frontend",
  },
  {
    id: "sana",
    name: "Sana",
    role: "Security Engineer",
    skills: ["Auth", "OWASP", "Privacy"],
    covers: ["Security", "Backend"],
    needsSupportWith: "Product",
  },
  {
    id: "kabir",
    name: "Kabir",
    role: "IoT Engineer",
    skills: ["ESP32", "Sensors", "MQTT"],
    covers: ["IoT", "Data"],
    needsSupportWith: "Backend",
  },
  {
    id: "zoya",
    name: "Zoya",
    role: "Growth & Community",
    skills: ["Storytelling", "Community", "Partnerships"],
    covers: ["Growth", "Product"],
    needsSupportWith: "Frontend",
  },
];

export const CHALLENGES: Challenge[] = [
  {
    id: "c1",
    name: "AI Study Buddy",
    prompt: "Build a study companion that helps college students understand difficult material and stay on track.",
    required: ["AI/ML", "Backend", "UI/UX", "Product"],
    bonus: ["Frontend", "Data"],
  },
  {
    id: "c2",
    name: "Zero-Waste Campus",
    prompt: "Reduce food waste across college canteens using technology.",
    required: ["Mobile", "Backend", "Data", "Product"],
    bonus: ["UI/UX", "Growth"],
  },
  {
    id: "c3",
    name: "Emergency Response Network",
    prompt: "Help students and campus staff coordinate quickly during emergencies.",
    required: ["Mobile", "Backend", "Cloud/DevOps", "Product"],
    bonus: ["Security", "Data"],
  },
  {
    id: "c4",
    name: "Mental Wellness Companion",
    prompt: "Create a private, approachable digital companion for student wellbeing.",
    required: ["UI/UX", "Product", "Backend", "Security"],
    bonus: ["AI/ML", "Mobile"],
  },
  {
    id: "c5",
    name: "Smart Energy Campus",
    prompt: "Use sensors and software to reduce unnecessary energy consumption on campus.",
    required: ["IoT", "Backend", "Data", "Cloud/DevOps"],
    bonus: ["Frontend", "Product"],
  },
  {
    id: "c6",
    name: "Cyber Safety Coach",
    prompt: "Help non-technical users recognize scams, unsafe links and risky online behaviour.",
    required: ["Security", "Backend", "Frontend", "Product"],
    bonus: ["AI/ML", "UI/UX"],
  },
  {
    id: "c7",
    name: "Local Business Growth OS",
    prompt: "Help small local businesses manage customers and grow digitally.",
    required: ["Frontend", "Backend", "Product", "Growth"],
    bonus: ["Data", "UI/UX"],
  },
  {
    id: "c8",
    name: "Accessible Campus Navigator",
    prompt: "Help students navigate campus more easily, including accessibility-aware routes.",
    required: ["Mobile", "UI/UX", "Backend", "Data"],
    bonus: ["Product", "Security"],
  },
];
